//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSalesSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.IMPORTRECEIPTs = new HashSet<IMPORTRECEIPT>();
            this.MAINTENANCEBILLs = new HashSet<MAINTENANCEBILL>();
            this.SELLBILLs = new HashSet<SELLBILL>();
        }
    
        public string EMP_ID { get; set; }
        public string EMP_NAME { get; set; }
        public string EMP_ACCOUNT { get; set; }
        public Nullable<System.DateTime> EMP_DATE_OF_BIRTH { get; set; }
        public string GENDER { get; set; }
        public string PHONE { get; set; }
        public string EMP_ADDRESS { get; set; }
        public Nullable<System.DateTime> DATE_OF_WORK { get; set; }
        public Nullable<decimal> SALARY { get; set; }
        public byte[] IMG { get; set; }
        public string EMP_TYPE { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<int> DateOfWork { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMPORTRECEIPT> IMPORTRECEIPTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAINTENANCEBILL> MAINTENANCEBILLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SELLBILL> SELLBILLs { get; set; }
    }
}
