//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSalesSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORTRECEIPTINFO
    {
        public string IRECEIPT_ID { get; set; }
        public string PRO_ID { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<decimal> IMPORT_PRICE { get; set; }
    
        public virtual IMPORTRECEIPT IMPORTRECEIPT { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
