//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSalesSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAINTENANCEBILL
    {
        public string MB_ID { get; set; }
        public Nullable<System.DateTime> MB_DATE { get; set; }
        public string CUSTOMER_ID { get; set; }
        public string PRO_ID { get; set; }
        public string EMPLOYEE_ID { get; set; }
        public Nullable<decimal> TOTALFEE { get; set; }
        public string BILL_STATUS { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
