//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSalesSystem.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CARSALESSYSTEMEntities : DbContext
    {
        public CARSALESSYSTEMEntities()
            : base("name=CARSALESSYSTEMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT> ACCOUNTs { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual DbSet<IMPORTRECEIPT> IMPORTRECEIPTs { get; set; }
        public virtual DbSet<MAINTENANCEBILL> MAINTENANCEBILLs { get; set; }
        public virtual DbSet<ORDERBILL> ORDERBILLs { get; set; }
        public virtual DbSet<PRODUCER> PRODUCERs { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTs { get; set; }
        public virtual DbSet<RANK_MONEY> RANK_MONEY { get; set; }
        public virtual DbSet<SELLBILL> SELLBILLs { get; set; }
        public virtual DbSet<TYPEPRODUCT> TYPEPRODUCTs { get; set; }
        public virtual DbSet<IMPORTRECEIPTINFO> IMPORTRECEIPTINFOes { get; set; }
    }
}
