//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSalesSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERBILL
    {
        public string OB_ID { get; set; }
        public Nullable<System.DateTime> OB_DATEB { get; set; }
        public string CUSTOMER_ID { get; set; }
        public string PRO_ID { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public string RANK_ID { get; set; }
        public Nullable<decimal> TOTAL_PRICE { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual RANK_MONEY RANK_MONEY { get; set; }
    }
}
