//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSalesSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.MAINTENANCEBILLs = new HashSet<MAINTENANCEBILL>();
            this.ORDERBILLs = new HashSet<ORDERBILL>();
            this.IMPORTRECEIPTINFOes = new HashSet<IMPORTRECEIPTINFO>();
            this.SELLBILLs = new HashSet<SELLBILL>();
        }
    
        public string PRO_ID { get; set; }
        public string PRO_NAME { get; set; }
        public Nullable<int> STORAGE_NUMBER { get; set; }
        public Nullable<int> SELL_NUMBER { get; set; }
        public string IRECEIPT_ID { get; set; }
        public decimal PRICE { get; set; }
        public string TYPEPRO_ID { get; set; }
        public string PRODUCER_ID { get; set; }
        public byte[] IMG { get; set; }
        public Nullable<int> PRO_YEAR { get; set; }
        public string ENGINELAYOUT { get; set; }
        public Nullable<int> DISPLACEMENT { get; set; }
        public Nullable<int> MAXSPEED { get; set; }
        public Nullable<int> MAXPOWER { get; set; }
        public string ACCELERATION { get; set; }
        public string TRACTION { get; set; }
    
        public virtual IMPORTRECEIPT IMPORTRECEIPT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAINTENANCEBILL> MAINTENANCEBILLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERBILL> ORDERBILLs { get; set; }
        public virtual PRODUCER PRODUCER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMPORTRECEIPTINFO> IMPORTRECEIPTINFOes { get; set; }
        public virtual TYPEPRODUCT TYPEPRODUCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SELLBILL> SELLBILLs { get; set; }
    }
}
